### ISSUE TITLE
no auto-selected answer

### ISSUE THREAD

**Issue by sihrus** [junzhiwang/Askme#1]
Very first question... "Yes" shouldn't be pre-selected. A bit odd to have to click on something already selected in order to hit next.

**Comment by junzhiwang** [comment]
I fixed it by preselect the first choice for all quesitons. Right now no need to click on any item before  entering 'next', the first choice is the default.

**Comment by sihrus** [comment]
This needs to be extended for the eligibility question. "Yes" cannot be pre-selected.
