### ISSUE TITLE
Log back in to mobile, weird activity

### ISSUE THREAD

**Issue by sihrus** [junzhiwang/Askme#19]
When I logged back in the mobile version after not using, the app acts a bit funny when I start using it. The questions stopped working, i.e. I couldn't answer the next question. Also, the "level up" screen popped up randomly when it shouldn't have (considering I didn't answer a question and definitely didn't get a point).

**Comment by junzhiwang** [comment]
It's stable for now based on my test. Sometimes it's just slow on the backend to give a response. But for newly created accounts played on the new backend, the issue may no longer exist.
