### ISSUE TITLE
Redesign main screen for desktop

### ISSUE THREAD

**Issue by sihrus** [junzhiwang/Askme#23]
I think one way to improve the design and fix this problem is by moving the entire right-most pain (i.e. the pane that contains all the answer choices, the sliders, etc) to the bottom of the screen and make it wide instead of tall and on the right side.I think this is also more familiar to people as that's how chatrooms, gmail, text messaging, slack, etc is on a desktop. See hand-drawn picture on slack.

**Comment by junzhiwang** [comment]
Fixed.

**Comment by junzhiwang** [comment]
Fixed
