### ISSUE TITLE
Buggy Asker

### ISSUE THREAD

**Issue by sihrus** [junzhiwang/Askme#24]
See attached... level-up happened twice in a row (I'm not sure which was the incorrect of the two). And the Asker appears to have reset after the first question. This does not appear to have been tested. 

![image](https://user-images.githubusercontent.com/15987078/31131381-0626def4-a828-11e7-995f-244c70ef1e46.png)

**Comment by sihrus** [comment]
Ah, I realized this happens when "0" is selected for a slider question. This should make the bug easier to fix.

**Comment by junzhiwang** [comment]
Fixed

**Comment by junzhiwang** [comment]
Fixed
