### ISSUE TITLE
Matrix image on mobile too big

### ISSUE THREAD

**Issue by sihrus** [junzhiwang/Askme#32]
![image](https://user-images.githubusercontent.com/15987078/31134818-373aa38c-a831-11e7-92a0-1c947044f3b9.png)

**Comment by sihrus** [comment]
This is true of the reading the eyes test too

**Comment by junzhiwang** [comment]
Looks good now.

**Comment by junzhiwang** [comment]
To make the above scenario reappear, keep selecting ask me something else until "intelligence" or "matrixes" appears. These 2 categories include questions containing images.
