### ISSUE TITLE
On desktop version, slider and "next" position

### ISSUE THREAD

**Issue by sihrus** [junzhiwang/Askme#36]
On the desktop version, for slider questions, can you put a little more blank space between the slider (particularly the slider labels) and the next button? I just mean move the "Next" button down a little bit so there's room between the slider labels and the next button.

**Comment by sihrus** [comment]
Actually, it might be easier and more versatile to space it so that the slider is 1/3 of the way down the screen, and the next button is 2/3 of the way down?

**Comment by sihrus** [comment]
Also, can we make the labels for the slider ("Agree", "Disagree", "Not at all", "Very", etc) next to the slider itself, not next to the "next" button? Right now, it's confusing I think.

**Comment by junzhiwang** [comment]
Looks fine now
