### ISSUE TITLE
"Imagine you unexpectedly received $1,000 today. How much of this amount would you donate to a good cause?"

### ISSUE THREAD

**Issue by sihrus** [junzhiwang/Askme#39]
I am not able to enter "0"

**Comment by sihrus** [comment]
Jake to ask Steven about it, likely backend issue

**Comment by junzhiwang** [comment]
Reinvestigate the issue, and found a tiny bug undiscovered by me ever before.
An interesting thing in Javascript is the judgment of (0 == '') (empty string) will return true, while I assumed it returns false before. That's the reason causing the issue. 
Fixed it. Just take some notes to prevent the same in the future.
