### ISSUE TITLE
Email authentication 

### ISSUE THREAD

**Issue by sihrus** [junzhiwang/Askme#43]
Once enter email address, send that email address an email to verify; click link to verify

**Comment by junzhiwang** [comment]
Found a feasible solution on https://firebase.google.com/docs/auth/custom-email-handler
Will finish this week.

**Comment by sihrus** [comment]
As discussed, Jake using his personal firebase account for dev; will switch to account we already have for production; Steven to send Jake account information we're using for Android version (won't interfere, create a "new app")

**Comment by junzhiwang** [comment]
Implemented by blocking users from login until the email is verified. 
The email title and content are modifiable.

**Comment by junzhiwang** [comment]
Can use registered email addresses to do the verification.

**Comment by sihrus** [comment]
Although it works, it takes more clicks than it should. I'm not sure there's an easy way to change that. 

At the very least, you need to fix the way this dialogue box looks so its more professional. (see attached) You're missing a period, and the text is jumbled so that the "X" in the corner looks like part of the word -- there needs to be more space between the text and the borders. I also think you should change the buttons so they're aligned vertically -- "Send verification email" on the top, and "Sign in" on the bottom. Please be consistent with capitalization.
![img_1258](https://user-images.githubusercontent.com/15987078/34216832-7e7a72da-e577-11e7-832d-96959f20b11c.PNG)

**Comment by junzhiwang** [comment]
Fixed.
