### ISSUE TITLE
“Scroll down to see full options”

### ISSUE THREAD

**Issue by sihrus** [junzhiwang/Askme#54]
Only able to test on desktop for now, but can we improve “Scroll down to see full options” to "Scroll to see all of your options". Also, can we somehow make it bigger? I nearly missed it. Or else, make it stay up there for longer.

Also, can we add little scroll bars to the right of the top and bottom Asker panes? It doesn't really look like a scrollable pane. I think the scroll bars would look best to the left of the score keeper

**Comment by junzhiwang** [comment]
Partial fixed. I made it stay 5 seconds.
For the second requirement, need investigation.

**Comment by junzhiwang** [comment]
Scrollbar visible on the PC version. A tiny CSS style change.
