### ISSUE TITLE
Risk question results in dead state on mobile

### ISSUE THREAD

**Issue by sihrus** [junzhiwang/Askme#58]
After submitting the ethnicity question, the risk question comes up, but I cannot answer it -- no slider appears. See attached.

![img_9698](https://user-images.githubusercontent.com/15987078/33225793-68e4b758-d14c-11e7-82a8-b9f8e0dfaa5c.PNG)

Please more carefully test.

**Comment by sihrus** [comment]
I reloaded the page, and logged back in, and now the slider appears with the question, but I cannot submit an answer. I keep clicking "Next" and nothing happens, no matter what answer I select.

**Comment by junzhiwang** [comment]
I tested locally and seems fine. Maybe sometimes it suffers backend slow response.
Will add some log info in the frontend this week. 
![issue58](https://user-images.githubusercontent.com/21269896/33330050-ad90bcee-d412-11e7-993d-1ed8ff6628b2.png)

**Comment by junzhiwang** [comment]
Fixed.
